apiVersion: v1
kind: Service
metadata:
  name: removercontatos
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: removercontatos
  ports:
    - name: http
      port: 8090
      targetPort: 8090
      nodePort: 30098
    - name: metrics
      port: 8091
      targetPort: 8091
      nodePort: 30091
