apiVersion: apps/v1
kind: Deployment
metadata:
  name: adicionarcontatos
  namespace: monitoring
  labels:
    app: adicionarcontatos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adicionarcontatos
  template:
    metadata:
      labels:
        app: adicionarcontatos
    spec:
      containers:
        - name: adicionarcontatos
          image: b1tech/adicionarcontatos:latest
          ports:
            - containerPort: 8086
            - containerPort: 8087
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
