apiVersion: v1
kind: Service
metadata:
  name: adicionarcontatos
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: adicionarcontatos
  ports:
    - name: http
      port: 8086
      targetPort: 8086
      nodePort: 30086
    - name: metrics
      port: 8087
      targetPort: 8087
      nodePort: 30087
