apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: monitoring
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: b1tech/cadastroauthentication:latest
          ports:
            - containerPort: 8082
            - containerPort: 8083
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
