apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      nodePort: 30082
    - name: metrics
      port: 8083
      targetPort: 8083
      nodePort: 30083
