apiVersion: v1
kind: Service
metadata:
  name: gatewayapi
spec:
  type: LoadBalancer
  selector:
    app: gatewayapi
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
