apiVersion: v1
kind: Service
metadata:
  name: consumeratualizarcontatos
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: consumeratualizarcontatos
  ports:
    - name: main
      port: 8094
      targetPort: 8094
      nodePort: 30994
    - name: metrics
      port: 8095
      targetPort: 8095
      nodePort: 30995
