apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gatewayapi-hpa
  labels:
    app: gatewayapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gatewayapi
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70 # 70% de uso da CPU
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80 # 80% de uso da memória
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 180
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
