apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-volume
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rabbitmq-pvc
