apiVersion: v1
kind: Service
metadata:
  name: atualizarcontatos
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: atualizarcontatos
  ports:
    - name: http
      port: 8088
      targetPort: 8088
      nodePort: 30088
    - name: metrics
      port: 8089
      targetPort: 8089
      nodePort: 30089
