apiVersion: v1
kind: Service
metadata:
  name: consumerremovercontatos
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: consumerremovercontatos
  ports:
    - name: main
      port: 8096
      targetPort: 8096
      nodePort: 30996
    - name: metrics
      port: 8097
      targetPort: 8097
      nodePort: 30997
